apiVersion: v1
kind: Service
metadata:
  name: {{ include "ayuskey.fullname" . }}
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - port: 3000
      protocol: TCP
      name: http
  selector:
		{{- include "ayuskey.selectorLabels" . | nindent 4 }}
