name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    services:
      postgres:
        image: postgres:11.2-alpine
        ports:
          - 54311:5432
        env:
          POSTGRES_DB: test-misskey
          POSTGRES_HOST_AUTH_METHOD: trust
      redis:
        image: redis:4.0-alpine
        ports:
          - 56311:6379

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: node devtools/diag-environment.js
    - run: sudo apt-get install -y ffmpeg
    - run: yarn install
    - run: yarn build
    - run: cp test/test.yml .config
    - run: yarn test
